CREATE DATABASE SONA;
USE [SONA];
CREATE TABLE STUDENT
(
 SROLL INT,
 SNAME VARCHAR(50),
 SMARKS INT,
 CITY VARCHAR(50),
 MOB CHAR(10),
 GENDER CHAR,
 DOB DATE
 );
 ALTER TABLE[dbo].[STUDENT] DROP COLUMN[MOB];
 ALTER TABLE [dbo].[STUDENT] ADD [MOB] CHAR(10);
 ALTER TABLE [dbo].[STUDENT] ALTER COLUMN [MOB] CHAR(12);
 DROP TABLE [dbo].[STUDENT];

 CREATE TABLE STUDENT
 (
   SROLL INT PRIMARY KEY IDENTITY(1,1),
   SNAME VARCHAR(50) NOT NULL,
   SMARKS INT CHECK (SMARKS>=0),
   CITY VARCHAR(50) DEFAULT 'DELHI',
   MOB VARCHAR(10) UNIQUE,
   GENDER CHAR,
   DOB DATE
   );
   INSERT INTO [dbo].[STUDENT]([SNAME],[SMARKS],[MOB],[GENDER],[DOB]) 
   VALUES ('SHIVATHMIKA',89,'9182320242','F','2005-03-08');
   INSERT INTO [dbo].[STUDENT]([SNAME],[SMARKS],[MOB],[GENDER],[DOB]) 
   VALUES ('SHIVA',67,'9182320245','F','2005-03-08');
   INSERT INTO [dbo].[STUDENT]([SNAME],[SMARKS],[MOB],[GENDER],[DOB]) 
   VALUES ('MONA',77,'9182920245','F','2008-05-01');

	SELECT * FROM [dbo].[STUDENT];
  
  ------FOREIGN KEY

  CREATE TABLE DEPT
  (
    DID INT PRIMARY KEY,
	DNAME VARCHAR(30),
	SROLL INT, FOREIGN KEY (SROLL) REFERENCES [dbo].[STUDENT]([SROLL])
	);
	INSERT INTO [dbo].[DEPT](DID,DNAME,SROLL) VALUES (2,'XYZ',2);
	SELECT * FROM [dbo].[DEPT];

	UPDATE [dbo].[STUDENT] SET [CITY]='BANGLORE' WHERE [SMARKS]=67;
	SELECT * FROM [dbo].[STUDENT];
	 DELETE FROM [dbo].[STUDENT] WHERE[CITY] ='BANGLORE';
	 SELECT * FROM [dbo].[STUDENT] WHERE [CITY] LIKE 'H%';
  




	


